/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src.View.SupScreen.Score;

/**
 *
 * @author minhg
 */
public class SupScreen_OptionScore extends javax.swing.JFrame {

    /**
     * Creates new form SupScreen_OptionScore
     */
    public SupScreen_OptionScore() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panAdd = new javax.swing.JPanel();
        btnUpdate4 = new javax.swing.JButton();
        btnUpdate5 = new javax.swing.JButton();
        btnUpdate6 = new javax.swing.JButton();
        btnUpdate7 = new javax.swing.JButton();
        lblUpdateScore = new javax.swing.JLabel();
        panAdd1 = new javax.swing.JPanel();
        btnUpdate8 = new javax.swing.JButton();
        btnUpdate9 = new javax.swing.JButton();
        btnUpdate10 = new javax.swing.JButton();
        btnUpdate11 = new javax.swing.JButton();
        panAdd2 = new javax.swing.JPanel();
        btnUpdate12 = new javax.swing.JButton();
        btnUpdate13 = new javax.swing.JButton();
        btnUpdate14 = new javax.swing.JButton();
        btnUpdate15 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panAdd.setBorder(javax.swing.BorderFactory.createTitledBorder("CURD"));

        btnUpdate4.setFont(new java.awt.Font("Segoe UI", 0, 29)); // NOI18N
        btnUpdate4.setText("ADD");
        btnUpdate4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate4ActionPerformed(evt);
            }
        });

        btnUpdate5.setFont(new java.awt.Font("Segoe UI", 0, 29)); // NOI18N
        btnUpdate5.setText("UPDATE");
        btnUpdate5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate5ActionPerformed(evt);
            }
        });

        btnUpdate6.setFont(new java.awt.Font("Segoe UI", 0, 29)); // NOI18N
        btnUpdate6.setText("REMOVE");
        btnUpdate6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate6ActionPerformed(evt);
            }
        });

        btnUpdate7.setFont(new java.awt.Font("Segoe UI", 0, 29)); // NOI18N
        btnUpdate7.setText("EXPORT");
        btnUpdate7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panAddLayout = new javax.swing.GroupLayout(panAdd);
        panAdd.setLayout(panAddLayout);
        panAddLayout.setHorizontalGroup(
            panAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAddLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnUpdate5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdate6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(btnUpdate7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdate4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panAddLayout.setVerticalGroup(
            panAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panAddLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnUpdate4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdate5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdate6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdate7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblUpdateScore.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblUpdateScore.setText("OPTION SCORE");

        panAdd1.setBorder(javax.swing.BorderFactory.createTitledBorder("SORT"));

        btnUpdate8.setFont(new java.awt.Font("Segoe UI", 0, 29)); // NOI18N
        btnUpdate8.setText("BY ID");
        btnUpdate8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate8ActionPerformed(evt);
            }
        });

        btnUpdate9.setFont(new java.awt.Font("Segoe UI", 0, 29)); // NOI18N
        btnUpdate9.setText("BY NAME");
        btnUpdate9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate9ActionPerformed(evt);
            }
        });

        btnUpdate10.setFont(new java.awt.Font("Segoe UI", 0, 29)); // NOI18N
        btnUpdate10.setText("BY SCORE");
        btnUpdate10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate10ActionPerformed(evt);
            }
        });

        btnUpdate11.setFont(new java.awt.Font("Segoe UI", 0, 29)); // NOI18N
        btnUpdate11.setText("BY AVERAGE");
        btnUpdate11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panAdd1Layout = new javax.swing.GroupLayout(panAdd1);
        panAdd1.setLayout(panAdd1Layout);
        panAdd1Layout.setHorizontalGroup(
            panAdd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAdd1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panAdd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnUpdate9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdate10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdate11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdate8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panAdd1Layout.setVerticalGroup(
            panAdd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panAdd1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUpdate8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdate9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdate10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdate11)
                .addContainerGap())
        );

        panAdd2.setBorder(javax.swing.BorderFactory.createTitledBorder("TOP 10"));

        btnUpdate12.setFont(new java.awt.Font("Segoe UI", 0, 29)); // NOI18N
        btnUpdate12.setText("ENGLISH");
        btnUpdate12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate12ActionPerformed(evt);
            }
        });

        btnUpdate13.setFont(new java.awt.Font("Segoe UI", 0, 29)); // NOI18N
        btnUpdate13.setText("COMPUTER");
        btnUpdate13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate13ActionPerformed(evt);
            }
        });

        btnUpdate14.setFont(new java.awt.Font("Segoe UI", 0, 29)); // NOI18N
        btnUpdate14.setText("PHYSICAL");
        btnUpdate14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate14ActionPerformed(evt);
            }
        });

        btnUpdate15.setFont(new java.awt.Font("Segoe UI", 0, 29)); // NOI18N
        btnUpdate15.setText("AVERAGE");
        btnUpdate15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panAdd2Layout = new javax.swing.GroupLayout(panAdd2);
        panAdd2.setLayout(panAdd2Layout);
        panAdd2Layout.setHorizontalGroup(
            panAdd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAdd2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panAdd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnUpdate13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdate14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdate15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdate12, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panAdd2Layout.setVerticalGroup(
            panAdd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panAdd2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUpdate12, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdate13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdate14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdate15)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUpdateScore)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUpdateScore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panAdd2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panAdd1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdate4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate4ActionPerformed

    private void btnUpdate5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate5ActionPerformed

    private void btnUpdate6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate6ActionPerformed

    private void btnUpdate7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate7ActionPerformed

    private void btnUpdate8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate8ActionPerformed

    private void btnUpdate9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate9ActionPerformed

    private void btnUpdate10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate10ActionPerformed

    private void btnUpdate11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate11ActionPerformed

    private void btnUpdate12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate12ActionPerformed

    private void btnUpdate13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate13ActionPerformed

    private void btnUpdate14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate14ActionPerformed

    private void btnUpdate15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupScreen_OptionScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupScreen_OptionScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupScreen_OptionScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupScreen_OptionScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupScreen_OptionScore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate10;
    private javax.swing.JButton btnUpdate11;
    private javax.swing.JButton btnUpdate12;
    private javax.swing.JButton btnUpdate13;
    private javax.swing.JButton btnUpdate14;
    private javax.swing.JButton btnUpdate15;
    private javax.swing.JButton btnUpdate4;
    private javax.swing.JButton btnUpdate5;
    private javax.swing.JButton btnUpdate6;
    private javax.swing.JButton btnUpdate7;
    private javax.swing.JButton btnUpdate8;
    private javax.swing.JButton btnUpdate9;
    private javax.swing.JLabel lblUpdateScore;
    private javax.swing.JPanel panAdd;
    private javax.swing.JPanel panAdd1;
    private javax.swing.JPanel panAdd2;
    // End of variables declaration//GEN-END:variables
}
